#!/usr/bin/env bash

tmp_dir="/tmp/cliphist"
if [[ -n "$1" ]]; then
    paste=1
else
    paste=0
fi

rm -rf "$tmp_dir"

mkdir -p "$tmp_dir"

read -r -d '' prog <<EOF
/^[0-9]+\s<meta http-equiv=/ { next }
match(\$0, /^([0-9]+)\s(\[\[\s)?binary.*(jpg|jpeg|png|bmp)/, grp) {
    system("echo " grp[1] "\\\\\t | cliphist decode >$tmp_dir/"grp[1]"."grp[3])
    print \$0"\0icon\x1f$tmp_dir/"grp[1]"."grp[3]
    next
}
1
EOF

output=$(cliphist list | gawk "$prog" | rofi -dmenu -display-columns 2 -show-icons -config ~/.config/rofi/config-clipboard.rasi)
output_status=$?

if [[ $output_status -eq 10 ]]; then
    cliphist wipe
    notify-send "Clipboard cleared"
elif [[ -n "$output" ]]; then
    cliphist decode <<<"$output" | wl-copy
    if [[ $paste -eq 1 ]]; then
        wtype -M ctrl -k v -m ctrl
    else
        notify-send "Copied to clipboard"
    fi
fi
